/**
 * AssistButton - Core trigger component that opens the assist menu
 *
 * Variants:
 * - "floating": Fixed position at bottom-right
 * - "inline": Inline with content flow
 *
 * Uses only CSS variables generated by the styling engine.
 * Zero external dependencies.
 * Appropriate ARIA attributes.
 */

export interface AssistButtonOptions {
  variant?: 'floating' | 'inline';
  label?: string;
  ariaLabel?: string;
}

export class AssistButton extends HTMLElement {
  private _variant: 'floating' | 'inline' = 'floating';
  private _label = '⚙️';
  private _ariaLabel = 'Open assist menu';
  private _button: HTMLButtonElement | null = null;

  static get observedAttributes() {
    return ['variant', 'label', 'aria-label'];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }

  connectedCallback() {
    this._variant =
      (this.getAttribute('variant') as 'floating' | 'inline') || 'floating';
    this._label = this.getAttribute('label') || '⚙️';
    this._ariaLabel =
      this.getAttribute('aria-label') ||
      this.getAttribute('ariaLabel') ||
      'Open assist menu';

    this.render();
    this.attachEventListeners();
  }

  attributeChangedCallback(name: string, oldValue: string, newValue: string) {
    if (oldValue === newValue) return;

    if (name === 'variant') {
      this._variant = (newValue as 'floating' | 'inline') || 'floating';
    } else if (name === 'label') {
      this._label = newValue || '⚙️';
    } else if (name === 'aria-label' || name === 'ariaLabel') {
      this._ariaLabel = newValue || 'Open assist menu';
    }

    if (this._button) {
      this.render();
    }
  }

  private render() {
    if (!this.shadowRoot) return;

    const variantClass = `assist-button--${this._variant}`;

    this.shadowRoot.innerHTML = `
      <style>
        :host {
          display: ${this._variant === 'inline' ? 'inline-block' : 'block'};
        }

        .assist-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: var(--neuroux-spacing-md, 12px);
          background: var(--neuroux-bg, #ffffff);
          border: 1px solid var(--neuroux-border, #e0e0e0);
          border-radius: var(--neuroux-radius-md, 8px);
          color: var(--neuroux-text, #1a1a2e);
          cursor: pointer;
          font-size: var(--neuroux-font-size-md, 16px);
          transition: all 0.2s ease;
          box-shadow: var(--neuroux-shadow-sm, 0 1px 3px rgba(0, 0, 0, 0.1));
          min-width: 44px;
          min-height: 44px;
        }

        .assist-button:hover {
          background: var(--neuroux-bg-hover, #f5f5f5);
          border-color: var(--neuroux-border-hover, #d0d0d0);
          box-shadow: var(--neuroux-shadow-md, 0 2px 6px rgba(0, 0, 0, 0.15));
        }

        .assist-button:focus {
          outline: var(--neuroux-focus-border, 2px solid var(--neuroux-accent, #88aaff));
          outline-offset: 2px;
          box-shadow: var(--neuroux-focus-shadow, 0 0 0 3px rgba(136, 170, 255, 0.3));
        }

        .assist-button:active {
          transform: scale(0.98);
        }

        .assist-button--floating {
          position: fixed;
          bottom: var(--neuroux-spacing-lg, 24px);
          right: var(--neuroux-spacing-lg, 24px);
          z-index: 9999;
        }

        .assist-button--inline {
          position: relative;
        }
      </style>
      <button
        class="assist-button ${variantClass}"
        aria-label="${this._ariaLabel}"
        aria-haspopup="true"
        aria-expanded="false"
        type="button"
      >
        ${this._label}
      </button>
    `;

    this._button = this.shadowRoot.querySelector('.assist-button');
  }

  private attachEventListeners() {
    if (!this._button) return;

    this._button.addEventListener('click', () => {
      const event = new CustomEvent('assist:open', {
        bubbles: true,
        cancelable: true,
      });
      this.dispatchEvent(event);

      // Update aria-expanded
      if (this._button) {
        const isExpanded =
          this._button.getAttribute('aria-expanded') === 'true';
        this._button.setAttribute('aria-expanded', String(!isExpanded));
      }
    });
  }

  // Public API
  public setExpanded(expanded: boolean) {
    if (this._button) {
      this._button.setAttribute('aria-expanded', String(expanded));
    }
  }
}

customElements.define('assist-button', AssistButton);
